# Generated by Django 5.0.7 on 2024-07-21 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('balanceapp', '0002_alter_customer_balance'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='description',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
