# Generated by Django 5.0.7 on 2024-07-25 09:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('balanceapp', '0003_alter_transaction_description'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customer',
            options={'ordering': ['id']},
        ),
        migrations.AlterModelOptions(
            name='transaction',
            options={'ordering': ['id']},
        ),
    ]
